# TODO: @memes - review and add/remove plugins
---
# spell-checker:disable
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        files: \.(yml|yaml|talismanrc)$
        types:
          - file
          - yaml
        entry: yamllint --strict
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      # TODO: @memes - remove/modify if push to main is allowed
      - id: no-commit-to-branch
        args:
          - -b
          - main
      - id: trailing-whitespace
  - repo: https://github.com/thoughtworks/talisman
    rev: v1.31.0
    hooks:
      - id: talisman-commit
