# spell-checker: disable
---
name: release

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6.3.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Run GoReleaser
        if: ${{ success() }}
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
      - name: Trigger Go Report update
        if: ${{ success() }}
        uses: fjogeleit/http-request-action@v1.16.4
        with:
          url: 'https://goreportcard.com/checks'
          method: 'POST'
          contentType: 'application/x-www-form-urlencoded'
          data: 'repo=github.com/${{ github.repository }}'
          preventFailureOnNoResponse: 'true'
